### ISSUE TITLE
Landsat data format different

### ISSUE THREAD

**Issue by ericbarefoot** [amoodie/shoreline_extract#2]
The data format as provided for level 1 landsat products has *been updated.* This code no longer has the configuration to correctly process the data. 

Bug discovered by @brandeeeee.

**Comment by amoodie** [comment]
bummer. Does @brandeeeee want to tackle the issue?

**Comment by amoodie** [comment]
@ericbarefoot @brandeeeee do we know if they updated the old files too or only new ones? There are a number of ways we could tackle this, and getting some more information up front to do some planning would be worthwhile.

**Comment by amoodie** [comment]
fixed with #3 on latest `master` push.
