### ISSUE TITLE
Error in reading "underscore" folders

### ISSUE THREAD

**Issue by huyquangtranaus** [amoodie/shoreline_extract#3]
Hi, Could you please help solve the error message below. I guess your code can't read the folder names/files that contain 'underscore" characters such as: LE07_L1TP_092087_20180117_20180212_01_T1

Thanks for help.

Error using regexp
The 'STRING' input must be either a char row vector, a cell array of char row vectors, or a string array.

Error in strsplit (line 125)
[c, matches] = regexp(str, aDelim, 'split', 'match');

Error in build_shorelineset>strip_from_meta (line 288)
    splt = strsplit(char(str),'=');

Error in build_shorelineset>get_metadata (line 250)
    [meta.clouds] = strip_from_meta(metadata, 'CLOUD_COVER', 'num');

Error in build_shorelineset>get_sortorder (line 124)
        [metadata{i, 1}] = get_metadata(meta,  fidmetadata, imagefolder);

Error in build_shorelineset (line 40)
    [sortidx, meta_sort] = get_sortorder(meta, folders, countfolders, meta.directory);

**Comment by amoodie** [comment]
Hi @huyquangt, thanks for your interest in the tool. @brandeeeee noticed this issue already (see #2) and created a fix, but I guess she has not pushed her changes. I will encourage her to do so asap.

That said, you can fix this problem by changing the code in `build_shorelineset.m` on [line 288](https://github.com/amoodie/shoreline_extract/blob/master/source/build_shorelineset.m#L288) to handle the parsing differently. If you come up with a solution, I invite your PR.

Cheers,
AM

**Comment by amoodie** [comment]
Hi @huyquangt, the issue should be resolved, with the new files on the `master` branch. You can go ahead and give it a try with your data.

For the record, the issue was not with underscores, but rather changes to metadata information. Will open an issue to handle these file changes better in the future. Thanks @brandeeeee  for the fix.
